language: php
php:
  - 5.4
  - 5.5
  - 5.6
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
services:
    - postgresql
before_script:
    - composer install
    - mysql -e "create database IF NOT EXISTS test;" -uroot
    - psql -c 'create database test;' -U root

script: phpunit -c phpunit.${DB}.xml