language: php
php:
  - 5.4
  - 5.5
  - 5.6
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
services:
    - postgresql
before_script:
    - composer install
script: phpunit --configuration phpunit.$DB.xml